services:
  # --- CAMADA DE SEGURANÇA (Proxy e Web Server) ---
  nginx:
    image: nginx:alpine
    container_name: nginx_waf
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cache:/etc/nginx/cache
      - wp_data:/var/www/html:ro # Para servir arquivos estáticos direto
    networks:
      - frontend
      - backend
    depends_on:
      - wordpress

  # --- CAMADA DE APLICAÇÃO (O Operário) ---
  wordpress:
    image: wordpress:fpm-alpine
    container_name: wp_app
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "@JaruOficial#2026$"
      WORDPRESS_DB_NAME: jaruoficial
      # Configurações para o Plugin S3 (MinIO)
      S3_UPLOADS_BUCKET: 'media-wp'
      S3_UPLOADS_KEY: 'admin_minio'
      S3_UPLOADS_SECRET: '@JaruOficial@2026#'
      S3_UPLOADS_REGION: 'us-east-1'
      S3_UPLOADS_ENDPOINT: 'http://minio:9000'
      # Configurações Redis
      WP_REDIS_HOST: redis_cache
    volumes:
      - wp_data:/var/www/html
      - ./wordpress/conf.d/performance.ini:/usr/local/etc/php/conf.d/zz-performance.ini
    networks:
      - backend
    depends_on:
      - mysql_db
      - redis_cache

  # --- CAMADA DE CACHE (A Turbina) ---
  redis_cache:
    image: redis:alpine
    container_name: wp_redis
    restart: always
    networks:
      - backend

  # --- CAMADA DE STORAGE (O Cofre de Mídia) ---
  minio:
    image: minio/minio
    container_name: minio_s3
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin_minio
      MINIO_ROOT_PASSWORD: "@JaruOficial@2026#"
    ports:
      - "9000:9000"  # API do MinIO (S3)
      - "9001:9001"  # Console do MinIO
    volumes:
      - minio_data:/data
    networks:
      - backend

  # --- CAMADA DE DADOS (O Coração) ---
  mysql_db:
    image: mysql:8.0
    container_name: wp_mysql
    restart: always
    environment:
      MYSQL_DATABASE: jaruoficial
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: "@JaruOficial#2026$"
      MYSQL_ROOT_PASSWORD: "@JaruOficial#2026$"
    command: --innodb-buffer-pool-size=256M --innodb-log-file-size=64M
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  # --- GERENCIAMENTO (phpMyAdmin) ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_db
    restart: always
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    depends_on:
      - mysql_db

  # --- GERENCIAMENTO (Portainer) ---
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"  # HTTPS
      - "8000:8000"  # Edge Agent (opcional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - frontend
      - backend


# --- REDES E VOLUMES ---
networks:
  frontend: # Aberta para a Internet
  backend:  # Privada para comunicação entre containers

volumes:
  wp_data:
    external: true
    name: sitewordpress_wp_data
  db_data:
    external: true
    name: sitewordpress_db_data
  minio_data:
  portainer_data:

